Fixes
fakE81/Shop_Warehouse_Project pull request #10
Opened 2022-07-08 06:11 UTC by fakE81

2022-07-08 07:13 UTC, ArnasPetraitis requested changes

2022-07-08 07:13 UTC, ArnasPetraitis commented on Shop/src/main/java/com/visma/internship/shop/services/WarehouseService.java
> +        String url = warehouseUrl + "/api/item/{id}";
warehouseUrl irgi galetu buti parametras `{url}/api/item/{id}`

2022-07-08 07:13 UTC, ArnasPetraitis commented on Shop/src/main/java/com/visma/internship/shop/services/WarehouseService.java
> +        String url = warehouseUrl + "/api/item/{id}";
kitas variantas yra autowire RestTemplateBuilder ir konstructoriuje is jo padaryti restTemplate su predefind situo url
```
restTemplate = restTemplateBuilder
                .rootUri(warehouseUrl)
                .build();
```

2022-07-08 07:13 UTC, ArnasPetraitis commented on Shop/src/main/java/com/visma/internship/shop/services/WarehouseService.java
> +        header.setAccept(Arrays.asList(MediaType.APPLICATION_OCTET_STREAM));
pasirasyk overloaded `setupHttpEntity(MediaType... accept)` arba papildyk esama, nes dabar kodo duplikavimo yra

2022-07-08 07:13 UTC, ArnasPetraitis commented on Shop/src/main/resources/templates/home.html
> -    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></s
o js tikrai nebereikalingas? gal ir nenaudoji...

2022-07-08 07:13 UTC, ArnasPetraitis commented on Shop/src/main/resources/templates/home.html
> +            <td th:if="${item.quantity > 0}"><a th:href="@{'/shop/item/sell/'+${item.id}}"
vietoj to paties elemento perrasymo galetum pabandyti tik elemento dalis itakoti, pvz `th:class="${item.quantity > 0}? 'btn btn-primary' : 'btn btn-primary disabled'"`

2022-07-08 07:13 UTC, ArnasPetraitis commented on Warehouse/src/main/java/com/visma/internship/warehouse/controllers/WarehouseController.java
> +        try{
nesuformatuotas tekstas ctrl+alt+L :)

2022-07-08 07:13 UTC, ArnasPetraitis commented on Warehouse/src/main/java/com/visma/internship/warehouse/controllers/WarehouseController.java
> +        try{
gal cia reiketu try-with-resources (nesu garantuotas)

2022-07-08 07:13 UTC, ArnasPetraitis commented on Warehouse/src/main/java/com/visma/internship/warehouse/report/ActivityReportScheduler.java
> +    public ActivityReportScheduler(ActivityRepositoryService activityRepositoryService, UserRepositoryService userRepositoryService) {
gal vistik sheduleris (kaip ir controler) turetu rupintis tik paleidimu, o visa logika eitu i service

2022-07-08 07:42 UTC, fakE81 commented on Warehouse/src/main/java/com/visma/internship/warehouse/controllers/WarehouseController.java
> +        try{
Turbut, kad ne. Nes reik duoti AutoCloseable o InputStreamResource netinka.

2022-07-08 09:56 UTC, ArnasPetraitis requested changes

2022-07-08 09:56 UTC, ArnasPetraitis commented on Shop/src/main/java/com/visma/internship/shop/services/WarehouseService.java
> +        header.setAccept(Arrays.asList(accept));
cia gal reiketu if accept != null

2022-07-08 09:56 UTC, ArnasPetraitis commented on Shop/src/main/java/com/visma/internship/shop/services/WarehouseService.java
> +    public WarehouseService(RestTemplateBuilder restTemplateBuilder) {
@Value buna priskiriams veliau todel contruktoriuje dar jo neturi, tai ispresti galima paduotant kaip konstruktoriaus argumenta `public WarehouseService(RestTemplateBuilder restTemplateBuilder, @Value("${warehouse.url}") warehouseUrl ) {`

2022-07-08 09:56 UTC, ArnasPetraitis commented on Warehouse/src/main/java/com/visma/internship/warehouse/report/ActivityReportService.java
> +    Logger logger = LoggerFactory.getLogger(ActivityReportScheduler.class);
reiketu access modifiers naudoti.
jei loggeris spring beane ir singleton tai naudojamas `private final` jei ne spring beansas o paprasta klase dazniausiai daroma `private static final`

2022-07-08 09:56 UTC, ArnasPetraitis commented on Warehouse/src/main/java/com/visma/internship/warehouse/report/ActivityReportService.java
> +            String filename = filepath + LocalTime.now().getHour() + ".csv";
cia turbut irgi turetu buti generateFileName panaudotas

2022-07-11 06:31 UTC, ArnasPetraitis approved these changes

2022-07-11 06:44 UTC, merged